### ISSUE TITLE
Livereload

### ISSUE THREAD

**Issue by katemihalikova** [coreskill/csss#2]
Přidat livereload, možná by stačilo počkat až na konverzi do Angularu.

**Comment by benabraham** [comment]
Pro vývoj nebo tím myslíš spuštěnou aplikaci?
Jinak asi jo, stačí později v obou případech.

**Comment by katemihalikova** [comment]
Pro vývoj. Zatím to máš v editoru :)

**Comment by katemihalikova** [comment]
Vyřešeno Angularem
